### ISSUE TITLE
Video demo

### ISSUE THREAD

**Issue by tombeers** [numirias/qtile-plasma#5]
From reading the readme, I'm finding it difficult to visualise how this layout works. Please consider adding a short video demo showing the basics of this layout.

**Comment by numirias** [comment]
Yep, I had planned on adding a screencast. I'll provide one in the next days.

**Comment by numirias** [comment]
Turned out I'm not great at doing screencasts, so I made [a gif](https://github.com/numirias/qtile-plasma#demo) showcasing the features. I hope that's enough to give you an initial idea how the layout works. :)
