### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by nazar-pc** [numirias/qtile-plasma#9]
I'm currently on `develop` branch of `qtile` and installed one with `pip3 install -e .`.

Does this layout support `develop` branch and how can I install it without replacing my current installation (`qtile-plasma` package loads stable version of `qtile` by dependencies). I'm not a Python developer, so question might be silly, but nevertheless.

**Comment by numirias** [comment]
The layout should run fine with the current  `develop` branch. Of course I can't guarantee that it won't introduce layout-breaking changes in the future.

If you want to install a package without dependencies you can do it like this:

    pip install qtile-plasma --upgrade --no-deps

**Comment by numirias** [comment]
Turns out I'm getting the same bug as #10.
